import { useMemo, useState, type FormEvent } from 'react';
import Image from 'next/image';
import { Activity, Camera, Check, Clock3, Dumbbell, Footprints, LoaderCircle, Plus, X, Trash2 } from 'lucide-react';
import { API_BASE } from '@/lib/api';
import { prepareImage } from '@/lib/image';
import { ProgressReport } from '@/types';
import type { Exercise } from '@/components/views/types';
import { PageHeading, EmptyState, todayString, niceDate } from '@/components/views/shared';
export function ActivityView({ onSave }: { onSave:(payload:unknown, photo?:File|null)=>Promise<void> }) {
  const [kind,setKind]=useState<'Strength'|'Walking'|'Sports'>('Strength'); const [day,setDay]=useState(todayString()); const [start,setStart]=useState('07:00'); const [end,setEnd]=useState('07:40'); const [notes,setNotes]=useState(''); const [rows,setRows]=useState<Exercise[]>([{exercise_name:'',weight:'',reps:'',sets:''}]); const [walking,setWalking]=useState({distance:'',steps:'',calories:'',avg_speed:''}); const [sport,setSport]=useState(''); const [photo,setPhoto]=useState<File|null>(null); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [saved,setSaved]=useState(false);
  const duration=useMemo(()=>{if(!start||!end)return 0; const [sh,sm]=start.split(':').map(Number);const [eh,em]=end.split(':').map(Number);return Math.max(0,eh*60+em-sh*60-sm);},[start,end]);
  function changeRow(i:number,key:keyof Exercise,value:string){setRows(old=>old.map((row,index)=>index===i?{...row,[key]:value}:row));}
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');setSaved(false);setSaving(true);try{const payload=kind==='Strength'?{kind,activity_date:day,start_time:start,end_time:end,notes,exercises:rows.map(r=>({exercise_name:r.exercise_name.trim(),weight:Number(r.weight),reps:Number(r.reps),sets:Number(r.sets)}))}:kind==='Walking'?{kind,activity_date:day,start_time:start,end_time:end,notes,walking:{distance:Number(walking.distance),steps:Number(walking.steps),calories:Number(walking.calories),avg_speed:Number(walking.avg_speed)}}:{kind,activity_date:day,start_time:start,end_time:end,notes,sport:{sport_name:sport.trim()}};await onSave(payload,photo?await prepareImage(photo):null);setSaved(true);setRows([{exercise_name:'',weight:'',reps:'',sets:''}]);setNotes('');setPhoto(null);setSport('');}catch(err){setError(err instanceof Error?err.message:'Could not save this activity.');}finally{setSaving(false);}}
  return <><PageHeading eyebrow="LOG YOUR MOVEMENT" title="New activity" subtitle="Record what you did. Your duration is calculated from the start and end times."/><section className="panel activity-form-panel"><div className="activity-type-switch"><button className={kind==='Strength'?'type-active':''} onClick={()=>setKind('Strength')} type="button"><Dumbbell size={17}/> Strength</button><button className={kind==='Walking'?'type-active':''} onClick={()=>setKind('Walking')} type="button"><Footprints size={17}/> Walking</button><button className={kind==='Sports'?'type-active':''} onClick={()=>setKind('Sports')} type="button"><Activity size={17}/> Sports</button></div>{error&&<div className="form-error">{error}</div>}{saved&&<div className="form-success"><Check size={15}/> Activity saved to your private history. Share it with friends from the feed when you’re ready.</div>}<form onSubmit={submit} className="activity-form"><div className="form-grid form-grid-three"><label>Date<input type="date" value={day} onChange={e=>setDay(e.target.value)} required/></label><label>Start time<input type="time" value={start} onChange={e=>setStart(e.target.value)} required/></label><label>End time<input type="time" value={end} onChange={e=>setEnd(e.target.value)} required/></label></div><div className="duration-preview"><Clock3 size={17}/><span>Calculated duration</span><strong>{duration ? `${duration} min` : 'Set an end time after start'}</strong></div>
    {kind==='Strength'?<div className="exercise-section"><div className="section-row"><div><b>Exercises</b><small>Add one row for each exercise.</small></div><button className="secondary-button small-button" type="button" onClick={()=>setRows(old=>[...old,{exercise_name:'',weight:'',reps:'',sets:''}])}><Plus size={15}/> Add exercise</button></div>{rows.map((row,i)=><div className="exercise-row" key={i}><label className="exercise-name">Exercise<input value={row.exercise_name} onChange={e=>changeRow(i,'exercise_name',e.target.value)} placeholder="e.g. Bench press" required/></label><label>Weight (kg)<input type="number" min="0" step="0.1" value={row.weight} onChange={e=>changeRow(i,'weight',e.target.value)} required/></label><label>Reps<input type="number" min="1" value={row.reps} onChange={e=>changeRow(i,'reps',e.target.value)} required/></label><label>Sets<input type="number" min="1" value={row.sets} onChange={e=>changeRow(i,'sets',e.target.value)} required/></label>{rows.length>1&&<button className="remove-row" type="button" aria-label="Remove exercise" onClick={()=>setRows(old=>old.filter((_,idx)=>idx!==i))}><X size={16}/></button>}</div>)}</div>:kind==='Walking'?<div className="form-grid form-grid-four walking-fields"><label>Distance (km)<input type="number" min="0" step="0.01" value={walking.distance} onChange={e=>setWalking({...walking,distance:e.target.value})} required/></label><label>Steps<input type="number" min="0" value={walking.steps} onChange={e=>setWalking({...walking,steps:e.target.value})} required/></label><label>Calories<input type="number" min="0" step="1" value={walking.calories} onChange={e=>setWalking({...walking,calories:e.target.value})} required/></label><label>Avg. speed (km/h)<input type="number" min="0" step="0.1" value={walking.avg_speed} onChange={e=>setWalking({...walking,avg_speed:e.target.value})} required/></label></div>:<label>Sport<input value={sport} onChange={e=>setSport(e.target.value)} maxLength={80} placeholder="e.g. Basketball, football, swimming" required/></label>}
    <label>Notes <span className="optional">Optional</span><textarea value={notes} onChange={e=>setNotes(e.target.value)} maxLength={1000} rows={3} placeholder="Add a note for your own history"/></label><label className="attach-button activity-photo"><Camera size={16}/><span>{photo?photo.name:'Attach a workout photo'}</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setPhoto(e.target.files?.[0]||null)}/></label><div className="form-bottom"><button className="primary-button" disabled={saving||duration<=0}>{saving?<LoaderCircle size={16} className="spin"/>:<Check size={16}/>} Save activity</button></div></form></section></>;
}

export function ProgressView({reports,onSave,onDelete}:{reports:ProgressReport[];onSave:(form:FormData)=>Promise<void>;onDelete:(id:number)=>void}) {
 const [day,setDay]=useState(todayString());const [notes,setNotes]=useState('');const [photo,setPhoto]=useState<File|null>(null);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [saved,setSaved]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError('');setSaved(false);const form=new FormData();form.set('report_date',day);form.set('notes',notes);try{if(photo)form.set('photo',await prepareImage(photo));await onSave(form);setSaved(true);setNotes('');setPhoto(null);}catch(err){setError(err instanceof Error?err.message:'Could not save report.');}finally{setSaving(false);}}
 return <><PageHeading eyebrow="PERSONAL CHECK-INS" title="Progress reports" subtitle="Keep a private record of how you feel and add a fitness photo when you want."/><div className="progress-layout"><section className="panel progress-form"><div className="panel-heading"><div><span className="panel-kicker">DAILY REPORT</span><h2>Log your progress</h2></div><Activity className="heading-icon" size={20}/></div>{error&&<div className="form-error">{error}</div>}{saved&&<div className="form-success"><Check size={15}/> Progress report saved.</div>}<form className="activity-form" onSubmit={submit}><label>Date<input type="date" value={day} onChange={e=>setDay(e.target.value)} required/></label><label>Notes <span className="optional">Optional</span><textarea rows={3} maxLength={1000} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="How are you feeling?"/></label><label className="attach-button activity-photo"><Camera size={16}/><span>{photo?photo.name:'Attach a progress photo'}</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setPhoto(e.target.files?.[0]||null)}/></label><button className="primary-button" disabled={saving}>{saving?<LoaderCircle size={16} className="spin"/>:<Check size={16}/>} Save report</button></form></section><section className="progress-history"><div className="panel-heading"><div><span className="panel-kicker">PRIVATE HISTORY</span><h2>{reports.length} check-ins</h2></div></div>{reports.map(r=><article className="panel progress-card" key={r.id}><div className="progress-date"><b>{niceDate(r.report_date)}</b><button className="danger-button small-button user-delete-button" onClick={()=>onDelete(r.id)}><Trash2 size={14}/> Delete</button></div>{r.notes&&<p>{r.notes}</p>}{r.image_url&&<Image src={`${API_BASE}${r.image_url}`} alt={`Progress photo for ${niceDate(r.report_date)}`} className="progress-image" width={1000} height={700} unoptimized/>}</article>)}{!reports.length&&<section className="panel"><EmptyState icon={Activity} title="Your check-ins will appear here" text="Add a private note or optional fitness photo to start your progress history."/></section>}</section></div></>;
}
