import { useEffect, useState, type FormEvent } from 'react';
import Image from 'next/image';
import { LoaderCircle, ShieldCheck, Users } from 'lucide-react';
import { API_BASE, api } from '@/lib/api';
import { AdminAccount, AdminReport, LeaderboardChanges } from '@/types';
import { initials, describeLeaderboardChanges, PageHeading, EmptyState, durationLabel, niceDate } from '@/components/views/shared';
export function AdminView({users,actorId,onLoadUser,onReloadUsers,onAdjustLeaderboard}:{users:AdminAccount[];actorId:number;onLoadUser:(id:number)=>Promise<AdminReport>;onReloadUsers:()=>Promise<AdminAccount[]>;onAdjustLeaderboard:(id:number,changes:LeaderboardChanges,reason:string)=>Promise<void>}) {
  const [selectedId,setSelectedId]=useState<number|null>(users[0]?.id??null);
  const [report,setReport]=useState<AdminReport|null>(null);
  const [loading,setLoading]=useState(false);
  const [error,setError]=useState('');
  async function refresh(){if(selectedId!==null)setReport(await onLoadUser(selectedId));await onReloadUsers();}
  async function removeMember(id:number){if(!window.confirm('Permanently delete this account and all of its workouts, progress reports, posts, comments, and uploaded images? This cannot be undone.'))return;setError('');try{await api.adminDeleteMember(id);const remaining=await onReloadUsers();if(id===selectedId){setReport(null);setSelectedId(remaining[0]?.id??null);}}catch(err){setError(err instanceof Error?err.message:'Could not delete account.');}}
  useEffect(()=>{if(selectedId===null)return;let cancelled=false;Promise.resolve().then(()=>{if(cancelled)return undefined;setLoading(true);setError('');return onLoadUser(selectedId);}).then(value=>{if(!cancelled&&value)setReport(value);}).catch(err=>{if(!cancelled)setError(err instanceof Error?err.message:'Could not load account data.');}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[selectedId,onLoadUser]);
  return <><PageHeading eyebrow="ROLE-BASED ACCESS" title="Admin console" subtitle="Review and edit member records, workout details, progress reports, and friend feed activity." action={<span className="private-pill"><ShieldCheck size={14}/> Administrator</span>}/>
    <section className="panel admin-members"><div className="panel-heading"><div><span className="panel-kicker">MEMBERS</span><h2>{users.length} accounts</h2></div></div>{users.length?<div className="responsive-table"><table><thead><tr><th>Member</th><th>Role</th><th>Total EXP</th><th>Workouts</th><th>Progress reports</th><th>Posts</th><th>Joined</th><th></th></tr></thead><tbody>{users.map(member=><tr key={member.id} className={member.id===selectedId?'current-user-row':''}><td><b>{member.display_name}</b><small className="admin-username">@{member.username}</small></td><td><span className="admin-role">{member.role}</span></td><td><b>{member.total_exp.toLocaleString()}</b></td><td>{member.workout_count}</td><td>{member.progress_count}</td><td>{member.post_count}</td><td>{niceDate(member.created_at)}</td><td className="admin-row-actions"><button className="secondary-button small-button" onClick={()=>setSelectedId(member.id)}>View data</button>{member.id!==actorId&&<button className="danger-button small-button" onClick={()=>void removeMember(member.id)}>Delete</button>}</td></tr>)}</tbody></table></div>:<EmptyState icon={Users} title="No accounts found" text="New member accounts will appear here."/>}</section>
    {error&&<div className="form-error">{error}</div>}{loading&&<div className="loading-line"><LoaderCircle size={16} className="spin"/> Loading member data…</div>}
      {report&&!loading&&<><section className="panel admin-user-summary"><span className="avatar">{initials(report.user.display_name)}</span><div><span className="panel-kicker">ACCOUNT RECORD</span><h2>{report.user.display_name} <small>@{report.user.username}</small></h2></div><span className="admin-role">{report.user.role}</span><b>{report.user.total_exp.toLocaleString()} EXP</b><span className="muted">Joined {niceDate(report.user.created_at)}</span></section>
      <AdminMemberEditor member={report.user} onSave={async(name)=>{await api.adminUpdateMember(report.user.id,name);await refresh();}} />
      <AdminLeaderboardEditor member={report.user} onSave={async(changes,reason)=>{await onAdjustLeaderboard(report.user.id,changes,reason);await refresh();}} />
      <section className="panel"><div className="panel-heading"><div><span className="panel-kicker">LEADERBOARD AUDIT</span><h2>{report.exp_adjustments.length} administrator adjustments</h2></div></div>{report.exp_adjustments.length?report.exp_adjustments.map((item,index)=><article className="admin-engagement" key={`${item.created_at}-${index}`}><div><b>{describeLeaderboardChanges(item)} · @{item.admin_username}</b><p>{item.reason}</p><small>{new Date(item.created_at).toLocaleString()}</small></div></article>):<p className="empty-inline">No leaderboard adjustments have been made.</p>}</section>
      <div className="admin-data-grid"><section className="panel"><div className="panel-heading"><div><span className="panel-kicker">WORKOUT HISTORY</span><h2>{report.workouts.length} activities</h2></div></div>{report.workouts.length?report.workouts.map(workout=><article className="admin-record" key={workout.id}><div className="progress-date"><b>{workout.workout_type}{workout.sport_name?` · ${workout.sport_name}`:''}</b><span>{niceDate(workout.workout_date)}</span></div><small>{durationLabel(workout.duration)} · {workout.start_time?.slice(0,5)}{workout.exp_amount?` · +${workout.exp_amount} EXP`:''}</small>{workout.notes&&<p>{workout.notes}</p>}<AdminWorkoutEditor workout={workout} onSave={async(payload)=>{await api.adminUpdateWorkout(report.user.id,workout.id,payload);await refresh();}}/><AdminDeleteButton label="Delete workout" onDelete={()=>api.adminDeleteWorkout(report.user.id,workout.id)} onDeleted={refresh}/>{workout.image_url&&<Image src={`${API_BASE}${workout.image_url}`} alt="Member workout attachment" className="admin-image" width={900} height={650} unoptimized/>}</article>):<p className="empty-inline">No workout records.</p>}</section>
      <section className="panel"><div className="panel-heading"><div><span className="panel-kicker">PROGRESS REPORTS</span><h2>{report.progress_reports.length} check-ins</h2></div></div>{report.progress_reports.length?report.progress_reports.map(progress=><article className="admin-record" key={progress.id}><div className="progress-date"><b>{niceDate(progress.report_date)}</b></div>{progress.notes&&<p>{progress.notes}</p>}<AdminProgressEditor report={progress} onSave={async(payload)=>{await api.adminUpdateProgress(report.user.id,progress.id,payload);await refresh();}}/><AdminDeleteButton label="Delete report" onDelete={()=>api.adminDeleteProgress(report.user.id,progress.id)} onDeleted={refresh}/>{progress.image_url&&<Image src={`${API_BASE}${progress.image_url}`} alt="Member progress attachment" className="admin-image" width={900} height={650} unoptimized/>}</article>):<p className="empty-inline">No progress reports.</p>}</section>
      <section className="panel"><div className="panel-heading"><div><span className="panel-kicker">FRIEND FEED POSTS</span><h2>{report.posts.length} posts</h2></div></div>{report.posts.length?report.posts.map(post=><article className="admin-record" key={post.id}><div className="progress-date"><b>{post.achievement_name?`Achievement · ${post.achievement_name}`:post.workout_id?`Workout · #${post.workout_id}`:'Post'}</b><span>{new Date(post.created_at).toLocaleDateString()}</span></div>{post.caption&&<p>{post.caption}</p>}<small>{post.likes_count} likes · {post.comments_count} comments</small><AdminPostEditor caption={post.caption} onSave={async(caption)=>{await api.adminUpdatePost(report.user.id,post.id,caption);await refresh();}}/><AdminDeleteButton label="Delete post" onDelete={()=>api.adminDeletePost(report.user.id,post.id)} onDeleted={refresh}/>{post.image_url&&<Image src={`${API_BASE}${post.image_url}`} alt="Member feed attachment" className="admin-image" width={900} height={650} unoptimized/>}</article>):<p className="empty-inline">No posts.</p>}</section>
      <section className="panel"><div className="panel-heading"><div><span className="panel-kicker">POST ENGAGEMENT</span><h2>{report.comments.length} comments · {report.likes.length} likes</h2></div></div>{report.comments.map(comment=><article className="admin-engagement" key={`c-${comment.id}`}><div><b>{comment.commenter} commented on post #{comment.post_id}</b><p>{comment.body}</p><small>{new Date(comment.created_at).toLocaleString()}</small></div><AdminDeleteButton label="Delete comment" onDelete={()=>api.adminDeleteComment(report.user.id,comment.id)} onDeleted={refresh}/></article>)}{report.likes.map((like,index)=><article className="admin-engagement" key={`l-${like.post_id}-${index}`}><b>{like.liker} liked post #{like.post_id}</b><small>{new Date(like.created_at).toLocaleString()}</small></article>)}{!report.comments.length&&!report.likes.length&&<p className="empty-inline">No post engagement.</p>}</section></div></>}
  </>;
}

export function AdminMemberEditor({member,onSave}:{member:AdminAccount;onSave:(name:string)=>Promise<void>}){
 const [open,setOpen]=useState(false);const [name,setName]=useState(member.display_name);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{await onSave(name);setOpen(false);}catch(err){setError(err instanceof Error?err.message:'Could not update member.');}finally{setBusy(false);}}
 return <div className="admin-editor"><button type="button" className="secondary-button small-button" onClick={()=>{setName(member.display_name);setOpen(v=>!v);}}>Edit member name</button>{open&&<form className="admin-edit-form" onSubmit={submit}>{error&&<span className="form-error">{error}</span>}<label>Display name<input value={name} onChange={e=>setName(e.target.value)} maxLength={80} required/></label><div className="admin-edit-actions"><button className="primary-button small-button" disabled={busy}>{busy?'Saving…':'Save name'}</button><button type="button" className="secondary-button small-button" onClick={()=>setOpen(false)}>Cancel</button></div></form>}</div>;
}

export function AdminLeaderboardEditor({member,onSave}:{member:AdminAccount;onSave:(changes:LeaderboardChanges,reason:string)=>Promise<void>}){
 const empty:LeaderboardChanges={amount:0,weekly_amount:0,monthly_amount:0,current_streak_delta:0,longest_streak_delta:0,workout_delta:0};
 const fields:Array<[keyof LeaderboardChanges,string]>=[['amount','Total EXP'],['weekly_amount','This week'],['monthly_amount','This month'],['current_streak_delta','Current streak (days)'],['longest_streak_delta','Best streak (days)'],['workout_delta','Workouts']];
 const [open,setOpen]=useState(false);const [changes,setChanges]=useState<LeaderboardChanges>(empty);const [reason,setReason]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!Object.values(changes).some(Boolean)){setError('Enter at least one non-zero change.');return;}setBusy(true);setError('');try{await onSave(changes,reason);setChanges(empty);setReason('');setOpen(false);}catch(err){setError(err instanceof Error?err.message:'Could not adjust leaderboard values.');}finally{setBusy(false);}}
 return <div className="admin-editor"><button type="button" className="secondary-button small-button" onClick={()=>setOpen(v=>!v)}>Adjust leaderboard</button>{open&&<form className="admin-edit-form" onSubmit={submit}>{error&&<span className="form-error">{error}</span>}<p className="muted">Current values: {member.total_exp.toLocaleString()} EXP · {member.weekly_exp.toLocaleString()} this week · {member.monthly_exp.toLocaleString()} this month · {member.current_streak} day streak · {member.longest_streak} best · {member.workout_count} workouts. Enter signed changes; rank updates automatically.</p><div className="admin-edit-grid">{fields.map(([key,label])=><label key={key}>{label}<input type="number" min={key==='current_streak_delta'||key==='longest_streak_delta'?-100_000:-1_000_000} max={key==='current_streak_delta'||key==='longest_streak_delta'?100_000:1_000_000} step={1} value={changes[key]} onChange={e=>setChanges(previous=>({...previous,[key]:Number(e.target.value)}))}/></label>)}</div><p className="empty-inline">Total EXP changes also affect this week and this month. Add a separate change to those fields only if needed.</p><label>Reason<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={250} rows={2} placeholder="Explain this adjustment" required/></label><div className="admin-edit-actions"><button className="primary-button small-button" disabled={busy}>{busy?'Saving…':'Save changes'}</button><button type="button" className="secondary-button small-button" onClick={()=>setOpen(false)}>Cancel</button></div></form>}</div>;
}

export function AdminWorkoutEditor({workout,onSave}:{workout:AdminReport['workouts'][number];onSave:(payload:unknown)=>Promise<void>}){
 const [open,setOpen]=useState(false);const [notes,setNotes]=useState(workout.notes||'');const [sportName,setSportName]=useState(workout.sport_name||'');
 const [exercises,setExercises]=useState(workout.exercises.map(x=>({exercise_name:x.exercise_name,weight:String(x.weight),reps:String(x.reps),sets:String(x.sets)})));
 const [walking,setWalking]=useState({distance:String(workout.walking?.distance??0),steps:String(workout.walking?.steps??0),calories:String(workout.walking?.calories??0),avg_speed:String(workout.walking?.avg_speed??0)});
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 function begin(){setNotes(workout.notes||'');setSportName(workout.sport_name||'');setExercises(workout.exercises.map(x=>({exercise_name:x.exercise_name,weight:String(x.weight),reps:String(x.reps),sets:String(x.sets)})));setWalking({distance:String(workout.walking?.distance??0),steps:String(workout.walking?.steps??0),calories:String(workout.walking?.calories??0),avg_speed:String(workout.walking?.avg_speed??0)});setOpen(v=>!v);}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const payload:Record<string,unknown>={notes};if(workout.workout_type==='Strength')payload.exercises=exercises.map(row=>({exercise_name:row.exercise_name.trim(),weight:Number(row.weight),reps:Number(row.reps),sets:Number(row.sets)}));else if(workout.workout_type==='Walking')payload.walking={distance:Number(walking.distance),steps:Number(walking.steps),calories:Number(walking.calories),avg_speed:Number(walking.avg_speed)};else payload.sport_name=sportName;try{await onSave(payload);setOpen(false);}catch(err){setError(err instanceof Error?err.message:'Could not update workout.');}finally{setBusy(false);}}
 function editExercise(index:number,key:string,value:string){setExercises(old=>old.map((row,i)=>i===index?{...row,[key]:value}:row));}
 return <div className="admin-editor"><button type="button" className="secondary-button small-button" onClick={begin}>Edit workout</button>{open&&<form className="admin-edit-form" onSubmit={submit}>{error&&<span className="form-error">{error}</span>}<label>Notes<textarea rows={2} value={notes} onChange={e=>setNotes(e.target.value)} maxLength={1000}/></label>{workout.workout_type==='Sports'&&<label>Sport<input value={sportName} onChange={e=>setSportName(e.target.value)} maxLength={80} required/></label>}{workout.workout_type==='Walking'&&<div className="admin-edit-grid">{(['distance','steps','calories','avg_speed'] as const).map(key=><label key={key}>{key.replace('_',' ')}<input type="number" min="0" step="0.1" value={walking[key]} onChange={e=>setWalking({...walking,[key]:e.target.value})} required/></label>)}</div>}{workout.workout_type==='Strength'&&<div className="admin-edit-exercises"><b>Exercises</b>{exercises.map((row,index)=><div className="admin-edit-grid" key={index}><label>Exercise<input value={row.exercise_name} onChange={e=>editExercise(index,'exercise_name',e.target.value)} maxLength={120} required/></label><label>Weight kg<input type="number" min="0" step="0.1" value={row.weight} onChange={e=>editExercise(index,'weight',e.target.value)} required/></label><label>Reps<input type="number" min="1" value={row.reps} onChange={e=>editExercise(index,'reps',e.target.value)} required/></label><label>Sets<input type="number" min="1" value={row.sets} onChange={e=>editExercise(index,'sets',e.target.value)} required/></label><button type="button" className="secondary-button small-button" disabled={exercises.length<=1} onClick={()=>setExercises(old=>old.filter((_,i)=>i!==index))}>Remove</button></div>)}<button type="button" className="secondary-button small-button" onClick={()=>setExercises(old=>[...old,{exercise_name:'',weight:'0',reps:'1',sets:'1'}])}>Add exercise</button></div>}<div className="admin-edit-actions"><button className="primary-button small-button" disabled={busy}>{busy?'Saving…':'Save workout'}</button><button type="button" className="secondary-button small-button" onClick={()=>setOpen(false)}>Cancel</button></div></form>}</div>;
}

export function AdminProgressEditor({report,onSave}:{report:AdminReport['progress_reports'][number];onSave:(payload:{notes:string})=>Promise<void>}){
 const [open,setOpen]=useState(false);const [notes,setNotes]=useState(report.notes||'');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{await onSave({notes});setOpen(false);}catch(err){setError(err instanceof Error?err.message:'Could not update report.');}finally{setBusy(false);}}
 return <div className="admin-editor"><button type="button" className="secondary-button small-button" onClick={()=>{setNotes(report.notes||'');setOpen(v=>!v);}}>Edit report</button>{open&&<form className="admin-edit-form" onSubmit={submit}>{error&&<span className="form-error">{error}</span>}<label>Notes<textarea rows={2} maxLength={1000} value={notes} onChange={e=>setNotes(e.target.value)}/></label><div className="admin-edit-actions"><button className="primary-button small-button" disabled={busy}>{busy?'Saving…':'Save report'}</button><button type="button" className="secondary-button small-button" onClick={()=>setOpen(false)}>Cancel</button></div></form>}</div>;
}

export function AdminPostEditor({caption,onSave}:{caption:string;onSave:(caption:string)=>Promise<void>}){
 const [open,setOpen]=useState(false);const [text,setText]=useState(caption);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{await onSave(text);setOpen(false);}catch(err){setError(err instanceof Error?err.message:'Could not update post.');}finally{setBusy(false);}}
 return <div className="admin-editor"><button type="button" className="secondary-button small-button" onClick={()=>{setText(caption);setOpen(v=>!v);}}>Edit caption</button>{open&&<form className="admin-edit-form" onSubmit={submit}>{error&&<span className="form-error">{error}</span>}<label>Caption<textarea rows={2} maxLength={500} value={text} onChange={e=>setText(e.target.value)}/></label><div className="admin-edit-actions"><button className="primary-button small-button" disabled={busy}>{busy?'Saving…':'Save caption'}</button><button type="button" className="secondary-button small-button" onClick={()=>setOpen(false)}>Cancel</button></div></form>}</div>;
}

export function AdminDeleteButton({label,onDelete,onDeleted}:{label:string;onDelete:()=>Promise<{deleted:boolean}>;onDeleted:()=>Promise<void>}){
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function remove(){if(!window.confirm(`Permanently ${label.toLowerCase()}? This cannot be undone.`))return;setBusy(true);setError('');try{await onDelete();await onDeleted();}catch(err){setError(err instanceof Error?err.message:`Could not ${label.toLowerCase()}.`);}finally{setBusy(false);}}
 return <div className="admin-delete-wrap"><button type="button" className="danger-button small-button" onClick={()=>void remove()} disabled={busy}>{busy?'Deleting…':label}</button>{error&&<span className="admin-delete-error">{error}</span>}</div>;
}
