import { useState, type FormEvent } from 'react';
import Image from 'next/image';
import { Activity, Camera, Check, Dumbbell, Footprints, Heart, ImagePlus, LoaderCircle, Send, Trophy, Users, X, Trash2 } from 'lucide-react';
import { API_BASE, api } from '@/lib/api';
import { prepareImage } from '@/lib/image';
import { Achievement, FeedComment, FeedPost, Workout } from '@/types';
import { initials, PageHeading, EmptyState, durationLabel, niceDate } from '@/components/views/shared';
export function FeedView({ posts, workouts, achievements, userId, onDeletePost, onShare }: { posts:FeedPost[]; workouts:Workout[]; achievements:Achievement[]; userId:number; onDeletePost:(id:number)=>void; onShare:(form:FormData)=>Promise<number> }) {
  const [caption,setCaption]=useState(''); const [workoutId,setWorkoutId]=useState(''); const [achievementId,setAchievementId]=useState('');
  const [includeWorkoutImage,setIncludeWorkoutImage]=useState(false); const [file,setFile]=useState<File|null>(null);
  const [sending,setSending]=useState(false); const [error,setError]=useState(''); const [sent,setSent]=useState(false);
  const chosenWorkout=workouts.find(w=>String(w.id)===workoutId);
  async function submit(e:FormEvent<HTMLFormElement>) {
    e.preventDefault(); setError(''); setSent(false);
    if (!workoutId&&!achievementId&&!file) { setError('Choose a workout, achievement, or screenshot before sharing.'); return; }
    setSending(true);
    try {
      const body=new FormData(); body.set('caption',caption);
      if(workoutId) body.set('workout_id',workoutId);
      if(achievementId) body.set('achievement_id',achievementId);
      body.set('include_workout_image',String(includeWorkoutImage));
      if(file) body.set('screenshot',await prepareImage(file));
      await onShare(body); setCaption(''); setWorkoutId(''); setAchievementId(''); setIncludeWorkoutImage(false); setFile(null); setSent(true);
    }
    catch(err) {setError(err instanceof Error?err.message:'Could not share this post.');}
    finally {setSending(false);}
  }
  return <><PageHeading eyebrow="YOUR FRIEND GROUP" title="Friends feed" subtitle="Share workouts, milestones, and the work behind them." />
    <div className="feed-layout"><div className="feed-stream"><section className="panel composer"><div className="composer-title"><span className="composer-avatar"><Camera size={18}/></span><div><b>Share a moment</b></div></div>{error&&<div className="form-error">{error}</div>}{sent&&<div className="form-success"><Check size={15}/> Shared with your friends.</div>}<form onSubmit={submit}><textarea value={caption} onChange={e=>setCaption(e.target.value)} maxLength={500} placeholder="What are you proud of today?" rows={3}/><div className="composer-controls"><div className="composer-tools"><label className="attach-button"><ImagePlus size={16}/><span>{file?file.name:'Add screenshot'}</span><input type="file" accept="image/png,image/jpeg,image/webp" disabled={includeWorkoutImage} onChange={e=>{setFile(e.target.files?.[0]||null);setIncludeWorkoutImage(false);}}/></label><select value={workoutId} onChange={e=>{setWorkoutId(e.target.value);setIncludeWorkoutImage(false);}} aria-label="Choose a workout to share"><option value="">Attach a workout</option>{workouts.map(w=><option value={w.id} key={w.id}>#{w.id} · {w.workout_type} · {niceDate(w.workout_date)}</option>)}</select><select value={achievementId} onChange={e=>setAchievementId(e.target.value)} aria-label="Choose an achievement to share"><option value="">Share an achievement</option>{achievements.map(a=><option value={a.id} key={`${a.id}-${a.badge_name}`}>{a.badge_name}</option>)}</select></div><button className="primary-button" disabled={sending}>{sending?<LoaderCircle size={16} className="spin"/>:<Send size={15}/>} Share</button></div>{chosenWorkout?.has_image&&<label className="include-image-option"><input type="checkbox" checked={includeWorkoutImage} onChange={e=>setIncludeWorkoutImage(e.target.checked)} disabled={Boolean(file)}/> Include this workout’s saved photo</label>}{file&&<div className="file-chip"><Camera size={14}/>{file.name}<button type="button" onClick={()=>{setFile(null);setIncludeWorkoutImage(false);}} aria-label="Remove screenshot"><X size={14}/></button></div>}</form></section>
      {posts.map(post=><FeedCard post={post} currentUserId={userId} onDeletePost={onDeletePost} key={post.id}/>)}{!posts.length&&<section className="panel"><EmptyState icon={Users} title="The feed is ready for your group" text="When you or a friend share a workout or screenshot, it’ll appear here." /></section>}
    </div></div></>;
}

export function FeedCard({ post, currentUserId, onDeletePost }: { post:FeedPost; currentUserId:number; onDeletePost:(id:number)=>void }) {
  const exp=post.exp_amount??0; const [liked,setLiked]=useState(post.liked_by_me); const [likes,setLikes]=useState(post.likes_count);
  const [commentsOpen,setCommentsOpen]=useState(false); const [comments,setComments]=useState<FeedComment[]>([]);
  const [commentsCount,setCommentsCount]=useState(post.comments_count); const [commentText,setCommentText]=useState('');
  const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  async function toggleLike(){setBusy(true);setError('');try{const result=liked?await api.unlike(post.id):await api.like(post.id);setLiked(result.liked);setLikes(result.likes_count);}catch(e){setError(e instanceof Error?e.message:'Could not update like.');}finally{setBusy(false);}}
  async function showComments(){const open=!commentsOpen;setCommentsOpen(open);setError('');if(open){try{setComments(await api.comments(post.id));}catch(e){setError(e instanceof Error?e.message:'Could not load comments.');}}}
  async function submitComment(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!commentText.trim())return;setBusy(true);setError('');try{await api.addComment(post.id,commentText);setCommentText('');setCommentsCount(n=>n+1);setComments(await api.comments(post.id));}catch(e){setError(e instanceof Error?e.message:'Could not add comment.');}finally{setBusy(false);}}
  async function removeComment(comment:FeedComment){if(!window.confirm('Delete your comment?'))return;setBusy(true);setError('');try{await api.deleteComment(post.id,comment.id);setComments(previous=>previous.filter(item=>item.id!==comment.id));setCommentsCount(count=>Math.max(0,count-1));}catch(e){setError(e instanceof Error?e.message:'Could not delete your comment.');}finally{setBusy(false);}}
  const icon=post.workout_type==='Walking'?<Footprints size={17}/>:post.workout_type==='Sports'?<Activity size={17}/>:<Dumbbell size={17}/>;
  return <article className="panel feed-card"><div className="feed-author"><span className="avatar">{initials(post.display_name)}</span><div><b>{post.display_name}</b><small>{new Date(post.created_at).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</small></div>{post.user_id===currentUserId&&<button className="danger-button small-button user-delete-button" onClick={()=>onDeletePost(post.id)} aria-label="Delete your post"><Trash2 size={14}/> Delete</button>}</div>{post.caption&&<p className="feed-caption">{post.caption}</p>}{post.workout_id&&<div className="shared-workout"><span className="workout-kind kind-strength">{icon}</span><div className="shared-workout-copy"><span className="panel-kicker">WORKOUT SHARED</span><b>{post.workout_type} · {durationLabel(post.duration)}</b><small>{niceDate(post.workout_date)}{exp?` · +${exp} EXP earned`:''}</small></div><span className="shared-check"><Check size={15}/></span></div>}{post.achievement_name&&<div className="shared-achievement"><span><Trophy size={18}/></span><div><small>ACHIEVEMENT SHARED</small><b>{post.achievement_name}</b></div></div>}{post.image_url&&<div className="feed-image-wrap"><Image src={`${API_BASE}${post.image_url}`} alt={`Workout image shared by ${post.display_name}`} className="feed-image" width={1200} height={900} unoptimized/></div>}<div className="feed-actions"><button className={`feed-action ${liked?'feed-action-liked':''}`} onClick={()=>void toggleLike()} disabled={busy}><Heart size={16} fill={liked?'currentColor':'none'}/><span>{likes} {likes===1?'like':'likes'}</span></button><button className="feed-action" onClick={()=>void showComments()}><Activity size={16}/><span>{commentsCount} comments</span></button></div>{error&&<div className="form-error">{error}</div>}{commentsOpen&&<section className="comments-panel">{comments.map(comment=><div className="comment-row" key={comment.id}><span className="avatar avatar-small">{initials(comment.display_name)}</span><div><b>{comment.display_name}</b><p>{comment.body}</p><small>{new Date(comment.created_at).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</small></div>{comment.user_id===currentUserId&&<button className="icon-button comment-delete-button" onClick={()=>void removeComment(comment)} disabled={busy} aria-label="Delete your comment" title="Delete your comment"><Trash2 size={14}/></button>}</div>)}{!comments.length&&<p className="empty-inline">No comments yet. Start the conversation.</p>}<form onSubmit={submitComment} className="comment-form"><input value={commentText} onChange={e=>setCommentText(e.target.value)} maxLength={500} placeholder="Write a comment…"/><button className="secondary-button small-button" disabled={busy||!commentText.trim()}>Comment</button></form></section>}</article>;
}
