import { useState, type FormEvent } from 'react';
import { Check, LoaderCircle, Plus, UserPlus, Users, X } from 'lucide-react';
import { api } from '@/lib/api';
import { Friend, FriendGroup, FriendList } from '@/types';
import { initials, PageHeading, EmptyState } from '@/components/views/shared';
export function FriendsView({ data, groups, onReload, onGroupsReload, onNotice }: { data:FriendList|null; groups:FriendGroup[]; onReload:()=>void; onGroupsReload:()=>void; onNotice:(message:string)=>void }) {
  const [username,setUsername]=useState('');const [loading,setLoading]=useState(false);const [error,setError]=useState('');
  async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError('');try{await api.addFriend(username);setUsername('');onNotice('Friend request sent.');onReload();}catch(err){setError(err instanceof Error?err.message:'Could not send the request.');}finally{setLoading(false);}}
  async function respond(id:number,accept:boolean){setLoading(true);setError('');try{await api.respondFriend(id,accept);onNotice(accept?'Friend request accepted.':'Friend request declined.');onReload();}catch(err){setError(err instanceof Error?err.message:'Could not update the request.');}finally{setLoading(false);}}
  return <><PageHeading eyebrow="YOUR PRIVATE GROUP" title="Friends" subtitle="Connect with people you know and organize them into groups."/><div className="friends-grid"><section className="panel friends-main"><div className="panel-heading"><div><span className="panel-kicker">ACCEPTED FRIENDS</span><h2>Your circle <span className="count-pill">{data?.friends.length??0}</span></h2></div><Users size={21} className="heading-icon"/></div>{data?.friends.length?<div className="friend-list">{data.friends.map(f=><div className="friend-row" key={f.username}><span className="avatar">{initials(f.display_name)}</span><div><b>{f.display_name}</b><small>@{f.username}</small></div><span className="friend-badge"><Check size={13}/> Friend</span></div>)}</div>:<EmptyState icon={Users} title="Your circle is waiting" text="Send a request to a friend to start your private group."/>}</section>
    <div className="friends-side"><section className="panel add-friend-card"><span className="panel-kicker">GROW YOUR CIRCLE</span><h2>Add a friend</h2><p>Send a request using their OneMoreRep username.</p>{error&&<div className="form-error">{error}</div>}<form onSubmit={add} className="add-friend-form"><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="Friend’s username" minLength={1} required/><button className="primary-button" disabled={loading}>{loading?<LoaderCircle size={16} className="spin"/>:<UserPlus size={16}/>} Send request</button></form></section>
    <section className="panel request-panel"><div className="panel-heading"><div><span className="panel-kicker">PENDING</span><h2>Incoming requests</h2></div><span className="count-pill">{data?.incoming.length??0}</span></div>{data?.incoming.length?data.incoming.map(req=><div className="friend-row request-row" key={req.id}><span className="avatar">{initials(req.display_name)}</span><div><b>{req.display_name}</b><small>@{req.username}</small></div><div className="request-actions"><button className="accept-button" disabled={loading} aria-label={`Accept ${req.display_name}`} onClick={()=>respond(req.id,true)}><Check size={15}/></button><button className="decline-button" disabled={loading} aria-label={`Decline ${req.display_name}`} onClick={()=>respond(req.id,false)}><X size={15}/></button></div></div>):<p className="empty-inline">No incoming requests.</p>}{data?.outgoing.map(friend=><div className="outgoing-row" key={friend.username}><span>{friend.display_name}</span><small>Request pending</small></div>)}</section></div></div><FriendGroupsPanel friends={data?.friends??[]} groups={groups} onReload={onGroupsReload} onNotice={onNotice}/></>;
}

export function FriendGroupsPanel({friends,groups,onReload,onNotice}:{friends:Friend[];groups:FriendGroup[];onReload:()=>void;onNotice:(message:string)=>void}){
 const [name,setName]=useState('');const [selected,setSelected]=useState<Record<number,string>>({});const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{await api.createGroup(name);setName('');onNotice('Friend group created.');onReload();}catch(err){setError(err instanceof Error?err.message:'Could not create group.');}finally{setBusy(false);}}
 async function add(groupId:number){setBusy(true);setError('');try{await api.addGroupMember(groupId,selected[groupId]||'');setSelected(old=>({...old,[groupId]:''}));onNotice('Friend added to group.');onReload();}catch(err){setError(err instanceof Error?err.message:'Could not add group member.');}finally{setBusy(false);}}
 async function remove(groupId:number,memberId:number){setBusy(true);setError('');try{await api.removeGroupMember(groupId,memberId);onNotice('Group membership updated.');onReload();}catch(err){setError(err instanceof Error?err.message:'Could not update group membership.');}finally{setBusy(false);}}
 async function discard(groupId:number){if(!window.confirm('Delete this friend group? Its members will remain friends.'))return;setBusy(true);setError('');try{await api.deleteGroup(groupId);onNotice('Friend group deleted.');onReload();}catch(err){setError(err instanceof Error?err.message:'Could not delete group.');}finally{setBusy(false);}}
 return <section className="panel friend-groups-panel"><div className="panel-heading"><div><span className="panel-kicker">YOUR CIRCLES</span><h2>Friend groups</h2></div><Users size={20} className="heading-icon"/></div><p className="muted">Make smaller circles for teams, training partners, or shared goals. Groups only include people who are already your friends.</p>{error&&<div className="form-error">{error}</div>}<form className="group-create-form" onSubmit={create}><input value={name} onChange={e=>setName(e.target.value)} maxLength={60} placeholder="Group name, e.g. Football" required/><button className="primary-button" disabled={busy}><Plus size={15}/> Create group</button></form>{groups.length?<div className="friend-groups-list">{groups.map(group=><article className="friend-group-card" key={group.id}><div className="panel-heading"><div><span className="panel-kicker">{group.is_owner?'GROUP OWNER':'MEMBER'}</span><h3>{group.name} <span className="count-pill">{group.members.length}</span></h3></div>{group.is_owner&&<button className="danger-button small-button" disabled={busy} onClick={()=>void discard(group.id)}>Delete group</button>}</div><div className="friend-group-members">{group.members.map(member=><div className="friend-row" key={member.id}><span className="avatar">{initials(member.display_name||'Friend')}</span><div><b>{member.display_name||'Friend'}</b>{member.username&&<small>@{member.username}</small>}</div>{member.id!==group.owner_id&&(group.is_owner||member.is_me)&&<button className="danger-button small-button" disabled={busy} onClick={()=>void remove(group.id,member.id)}>{member.is_me?'Leave group':'Remove'}</button>}</div>)}</div>{group.is_owner&&friends.length>0&&<form className="group-create-form" onSubmit={e=>{e.preventDefault();void add(group.id);}}><select aria-label={`Add a friend to ${group.name}`} value={selected[group.id]||''} onChange={e=>setSelected(old=>({...old,[group.id]:e.target.value}))} required><option value="">Choose a friend</option>{friends.filter(friend=>!group.members.some(member=>member.username===friend.username)).map(friend=><option value={friend.username} key={friend.username}>{friend.display_name}</option>)}</select><button className="secondary-button" disabled={busy||!selected[group.id]}><UserPlus size={15}/> Add member</button></form>}</article>)}</div>:<p className="empty-inline">Create a group to organize friends into circles.</p>}</section>;
}
