import { useState } from 'react';
import { Activity, Award, ChevronRight, Dumbbell, Footprints, Flame, LogOut, Sparkles, Trophy, Users, X, Trash2 } from 'lucide-react';
import { Achievement, ExpRecord, FriendGroup, LeaderboardRow, Statistics, User, Workout, WorkoutDetail } from '@/types';
import { initials, PageHeading, MetricCard, EmptyState, durationLabel, niceDate, nicePeriod } from '@/components/views/shared';
export function HistoryView({ rows, onShare, onDelete, onDetails }: { rows:Workout[]; onShare:()=>void; onDelete:(id:number)=>void; onDetails:(id:number)=>Promise<WorkoutDetail> }) {
  const [selected,setSelected]=useState<WorkoutDetail|null>(null);
  const [selectedId,setSelectedId]=useState<number|null>(null);
  const [detailError,setDetailError]=useState('');
  async function showDetails(id:number) {
    setDetailError('');
    try { setSelected(await onDetails(id)); setSelectedId(id); }
    catch(e) { setDetailError(e instanceof Error?e.message:'Could not load activity details.'); }
  }
  return <><PageHeading eyebrow="YOUR ACTIVITY" title="Workout history" subtitle="Every session you log stays here, whether or not you share it." action={<button className="secondary-button" onClick={onShare}><Users size={16}/> Share with friends</button>}/><section className="panel table-panel"><div className="panel-heading"><div><span className="panel-kicker">ALL SESSIONS</span><h2>{rows.length} activities</h2></div></div>{detailError&&<div className="form-error">{detailError}</div>}{rows.length?<div className="responsive-table"><table><thead><tr><th>Date</th><th>Activity</th><th>Start</th><th>Duration</th><th>EXP</th><th></th></tr></thead><tbody>{rows.map(w=><tr key={w.id}><td>{niceDate(w.workout_date)}</td><td><button className="table-kind detail-trigger" onClick={()=>void showDetails(w.id)} aria-label={`View ${w.workout_type} details`}>{w.workout_type==='Walking'?<Footprints size={15}/>:w.workout_type==='Sports'?<Activity size={15}/>:<Dumbbell size={15}/>} {w.workout_type}<ChevronRight size={13}/></button></td><td>{w.start_time?.slice(0,5)||'—'}</td><td>{durationLabel(w.duration)}</td><td><span className={`xp-chip ${w.exp_amount?'xp-earned':''}`}>{w.exp_amount?`+${w.exp_amount}`:'0'} EXP</span></td><td><button className="danger-button small-button user-delete-button" onClick={()=>onDelete(w.id)} aria-label="Delete your workout"><Trash2 size={14}/> Delete</button></td></tr>)}</tbody></table></div>:<EmptyState icon={Activity} title="No activities yet" text="Your logged workouts will appear here."/>}
    {selected&&<section className="activity-detail"><div className="panel-heading"><div><span className="panel-kicker">ACTIVITY DETAILS · #{selectedId}</span><h2>{selected.workout_type}</h2></div><button className="icon-button" onClick={()=>setSelected(null)} aria-label="Close activity details"><X size={17}/></button></div>{selected.workout_type==='Strength'?<div className="responsive-table"><table><thead><tr><th>Exercise</th><th>Weight</th><th>Reps</th><th>Sets</th></tr></thead><tbody>{selected.details.map((item,index)=><tr key={index}><td>{item.exercise_name}</td><td>{item.weight} kg</td><td>{item.reps}</td><td>{item.sets}</td></tr>)}</tbody></table></div>:<div className="detail-facts">{Object.entries(selected.details[0]??{}).map(([key,value])=><div key={key}><small>{key.replace('_',' ')}</small><b>{value}</b></div>)}</div>}</section>}
  </section></>;
}

export function ExpView({ rows }: { rows:ExpRecord[] }) {
  return <><PageHeading eyebrow="CONSISTENCY REWARDS" title="EXP history" subtitle="Workout rewards and any administrator adjustments to your balance."/><section className="panel table-panel"><div className="panel-heading"><div><span className="panel-kicker">EXP HISTORY</span><h2>{rows.reduce((n,r)=>n+r.exp_amount,0).toLocaleString()} total EXP</h2></div><Sparkles className="heading-icon" size={20}/></div>{rows.length?<div className="responsive-table"><table><thead><tr><th>Date</th><th>Period</th><th>Activity</th><th>Duration</th><th>EXP</th></tr></thead><tbody>{rows.map((r,i)=><tr key={`${r.activity_date}-${r.activity_period}-${i}`}><td>{niceDate(r.activity_date)}</td><td>{r.source==='admin_adjustment'?'Admin adjustment':nicePeriod(r.activity_period)}</td><td>{r.source==='admin_adjustment'?<>{r.reason}<small className="admin-username">Adjusted by @{r.admin_username}</small></>:r.workout_type}</td><td>{r.duration===null?'—':durationLabel(r.duration)}</td><td><span className={`xp-chip ${r.exp_amount>0?'xp-earned':''}`}>{r.exp_amount>0?'+':''}{r.exp_amount} EXP</span></td></tr>)}</tbody></table></div>:<EmptyState icon={Sparkles} title="Your first EXP is close" text="A session longer than 30 minutes in the morning or evening period earns EXP."/>}</section></>;
}

export function LeaderboardView({ rows, groups, currentId, onSelectGroup }: { rows:LeaderboardRow[]; groups:FriendGroup[]; currentId:number; onSelectGroup:(id:number|null)=>void }) {
  const [selected,setSelected]=useState('');
  function choose(value:string){setSelected(value);onSelectGroup(value?Number(value):null);}
  const title=groups.find(group=>String(group.id)===selected)?.name||'All friends';
  return <><PageHeading eyebrow="FRIENDLY COMPETITION" title="Leaderboard" subtitle="Compare consistency with all your friends or choose one of your groups."/><section className="panel table-panel"><div className="panel-heading"><div><span className="panel-kicker">FRIENDS LEADERBOARD</span><h2>{title}</h2></div><Trophy className="heading-icon" size={21}/></div><label className="leaderboard-scope">Show standings<select aria-label="Leaderboard group" value={selected} onChange={e=>choose(e.target.value)}><option value="">All friends</option>{groups.map(group=><option key={group.id} value={group.id}>{group.name}</option>)}</select></label>{rows.length?<div className="responsive-table"><table><thead><tr><th>Rank</th><th>Member</th><th>Total EXP</th><th>This week</th><th>This month</th><th>Streak</th><th>Workouts</th></tr></thead><tbody>{rows.map((row,index)=><tr className={row.id===currentId?'current-user-row':''} key={row.id}><td><span className={`rank-mark ${index<3?'rank-top':''}`}>{index+1}</span></td><td><span className="table-person"><span className="avatar avatar-small">{initials(row.display_name)}</span><b>{row.display_name}{row.id===currentId?' (you)':''}</b></span></td><td><b>{row.total_exp.toLocaleString()}</b></td><td>{row.weekly_exp}</td><td>{row.monthly_exp}</td><td>{row.current_streak} days <small className="muted">· best {row.longest_streak}</small></td><td>{row.total_workouts}</td></tr>)}</tbody></table></div>:<EmptyState icon={Trophy} title="No standings yet" text={selected?'Group members will appear here as they log activity.':'Add friends to see your private leaderboard.'}/>}</section></>;
}

export function StatisticsView({ data }: { data:Statistics|null }) {
  const items=[['Total EXP',data?.total_exp??0,Sparkles],['Total workouts',data?.total_workouts??0,Activity],['Strength workouts',data?.strength_workouts??0,Dumbbell],['Walking sessions',data?.walking_sessions??0,Footprints],['Sports sessions',data?.sports_sessions??0,Activity],['Weight lifted',`${Number(data?.total_weight??0).toLocaleString()} kg`,Award],['Walking distance',`${Number(data?.total_distance??0).toLocaleString()} km`,Footprints],['Total steps',Number(data?.total_steps??0).toLocaleString(),Activity],['Longest streak',`${data?.longest_streak??0} days`,Flame]] as const;
  return <><PageHeading eyebrow="YOUR CONSISTENCY, IN NUMBERS" title="Statistics" subtitle="Your totals come directly from your logged workouts and earned EXP."/><section className="stats-grid">{items.map(([label,value,Icon])=><MetricCard key={label} icon={Icon} label={label} value={value} note="All time" tone="blue"/>)}<MetricCard icon={Flame} label="Current streak" value={`${data?.current_streak??0} days`} note="Qualifying days in a row" tone="orange"/></section></>;
}

export function ProfileView({ user, stats, achievements, onSignOut }: { user:User; stats:Statistics|null; achievements:Achievement[]; onSignOut:()=>void }) {
  return <><PageHeading eyebrow="YOUR ACCOUNT" title="Profile" subtitle="Your OneMoreRep details, personal bests, and earned badges."/><section className="panel profile-panel"><div className="profile-hero"><span className="profile-avatar">{initials(user.display_name)}</span><div><h2>{user.display_name}</h2><p>@{user.username}</p></div></div><div className="profile-facts"><div><small>Current streak</small><b>{stats?.current_streak??0} days</b></div><div><small>Longest streak</small><b>{stats?.longest_streak??0} days</b></div><div><small>Total EXP</small><b>{(stats?.total_exp??0).toLocaleString()}</b></div><div><small>Logged activities</small><b>{stats?.total_workouts??0}</b></div></div><section className="achievement-section"><div className="panel-heading"><div><span className="panel-kicker">MILESTONES</span><h2>Your achievements <span className="count-pill">{achievements.length}</span></h2></div><Award size={20} className="heading-icon"/></div>{achievements.length?<div className="achievement-grid">{achievements.map(item=><div className="achievement-card" key={item.badge_name}><span><Trophy size={17}/></span><div><b>{item.badge_name}</b><small>Earned {niceDate(item.earned_at)}</small></div></div>)}</div>:<p className="empty-inline">Your first badge is waiting for your next milestone.</p>}</section><button className="secondary-button logout-button" onClick={onSignOut}><LogOut size={16}/> Log out</button></section></>;
}
